# This is a basic workflow to help you get started with Actions

name: Auto-change PR Base to Develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [ "opened", "edited", "reopened" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  change-base:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Change PR base to develop
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;

            if (context.payload.pull_request.base.ref === 'develop' || context.payload.pull_request.base.ref === 'hotfix') {
              console.log("No change needed.");
              return;
            }

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;

            await github.rest.pulls.update({
              owner, 
              repo, 
              pull_number, 
              base: 'develop'
            });

            console.log(`Changed base branch of PR #${pull_number} to 'develop'`);
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
        # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
