name: Auto-manage PR branches

on:
  pull_request:
    types: ["opened", "edited", "reopened"]

jobs:
  change-base:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require("./.github/workflows/auto-manage-pr-branches.js");
            script({ context, github });
